### ISSUE TITLE
Chinese character problem on Queue Button but not in Browse Button

### ISSUE THREAD

**Issue by R00t8ug** [pimusicbox/mopidy-musicbox-webclient#58] opened 2014-12-18 06:13 UTC
1. Click Browse > Local files  (I able to see the Chinese character without any problem)
2. After choose the song and play it will appear on Queue show  unreadable word.

Please help, is this bug?

**Comment by jcass77** [comment] 2016-02-13 09:44
I've been unable to reproduce this in the latest develop.

Browsing local files shows:

![skitched-20160213-114236](https://cloud.githubusercontent.com/assets/10268911/13027004/e465e570-d246-11e5-9c69-7effb4e8cb5d.png)

...and then in the queue:

![skitched-20160213-114351](https://cloud.githubusercontent.com/assets/10268911/13027011/0f7a5dea-d247-11e5-89f9-43c38f937887.png)

Closing for now, please open again if this is still an issue.

**Closed by jcass77** 2016-02-13 09:44 UTC
