### ISSUE TITLE
browsing local files doesn't save scroll position (i have a fix for this)

### ISSUE THREAD

**Issue by ogdento** [pimusicbox/mopidy-musicbox-webclient#93] opened 2015-04-04 04:01 UTC
I've got over 700 artists on a local drive and I want to scroll through them to add songs to my queue (i've got the feature to add files to queue from browse)...

The problem is when I scroll down to say "The Rolling Stones", add a file to my queue, and go Back to the list of artists, it starts at the beginning. To get back to or past "The Rolling Stones" I have to flip through hundreds of artists again.

I think it would be nice if it scrolled to or stayed at the last artist you were browsing.

If the bug/enhancement is accepted I can put in a fix

My fix:
In library.getBrowseDir(), I append :scrollY=xxxx to the browse stack item if I'm going into a directory or I get the scrollY position off the popped stack item if I'm backing out.
In process_ws.processBrowseDir(), I call window.scrollTo(0,scrollY) if scrollY > 0.
I also clean up the browse stack item to make sure we query mopidy with :scrollY=xxx in there

**Comment by kingosticks** [comment] 2015-04-05 21:03
To me this looks like a duplicate of https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues/73.

**Closed** 2017-02-16 22:20 UTC
