### ISSUE TITLE
Problems with Chrome after update

### ISSUE THREAD

**Issue by sterni1971** [pimusicbox/mopidy-musicbox-webclient#170] opened 2016-02-16 23:08 UTC
OS: Raspbian 8
Browser: Chrome 48.0.2564.109 / Linux
Mopidy: 2.0.0-1

I've updated Mopidy-MusicBox-Webclient to version 2.1.1 and afterwards
the  start page in "Chrome" looks strange, the side bar is hidden. And the
buttons don't work.

With firefox everythings works as expected.

**Comment by kingosticks** [comment] 2016-02-16 23:50
Have you tried forcing a page reload that ignores your cache? It should be ctrl + F5 or shift + F5. 

The webclient should not be getting this right but if you are coming from an old version perhaps it initially doesn't.

**Comment by jcass77** [comment] 2016-02-17 04:45
Like @kingosticks said, clearing the cache and forcing a reload should ensure that the page loads and displays properly.

This sometimes also happens if the web client cannot connect to Mopidy.

I think there is more work to be done to get our appcache to be [standards compliant](http://www.w3schools.com/html/html5_app_cache.asp) and work properly for offline access:

- ``mb.manifest`` should be renamed to ``mb.appcache`` to align with the emerging standard
- we need an ``OFFLINE`` section in the manifest file that redirects to a page that makes it clear that we cannot connect to Mopidy, instead of displaying the improperly formatted page

**Comment by jcass77** [comment] 2016-02-17 04:51
...correction: make that a ``FALLBACK`` section.

**Comment by sterni1971** [comment] 2016-02-17 20:03
So Itgried the shift+f5 and I expclicitlly cleared the cache same result. Even with chrome browser
on my android phone it don't work.

Here all I see in the mobidy log. I clicked all buttons, only alarmclock and setting show an reaction
(404 error) 

2016-02-17 20:57:51,377 INFO [6178:HttpServer] tornado.access: 302 GET / (192.168.1.3) 7.68ms
2016-02-17 20:57:51,406 INFO [6178:HttpServer] tornado.access: 304 GET /mopidy/ (192.168.1.3) 13.37ms
2016-02-17 20:57:51,469 INFO [6178:HttpServer] tornado.access: 304 GET /mopidy/mopidy.css (192.168.1.3) 13.24ms
2016-02-17 20:58:01,270 INFO [6178:HttpServer] tornado.access: 304 GET /musicbox_webclient/mb.manifest (192.168.1.3) 13.57ms
2016-02-17 20:58:01,470 INFO [6178:HttpServer] tornado.access: 304 GET /mopidy/mopidy.min.js (192.168.1.3) 13.15ms
2016-02-17 20:59:01,425 WARNING [6178:HttpServer] tornado.access: 404 GET /alarmclock/ (192.168.1.3) 8.28ms
2016-02-17 20:59:04,454 INFO [6178:HttpServer] tornado.access: 304 GET /musicbox_webclient/mb.manifest (192.168.1.3) 14.14ms
2016-02-17 20:59:34,112 WARNING [6178:HttpServer] tornado.access: 404 GET /settings/ (192.168.1.3) 9.08ms

**Comment by sterni1971** [comment] 2016-02-17 20:47
this what I see in th java console
```
Document was loaded from Application Cache with manifest http://music.local:6680/musicbox_webclient/mb.manifest
index.html:1 Application Cache Checking event
index.html:1 Application Cache NoUpdate event
gui.js:460 Uncaught ReferenceError: wsLocation is not defined
```

**Comment by jcass77** [comment] 2016-02-18 04:03
This sounds like a duplicate of #105, and was fixed in version 2.0.1. If you've already upgraded to 2.1.1 then something else is going on as the code referenced on line 460 of ``gui.js`` in the error message doesn't even exist anymore.

All I can think of is that Chrome is still managing to load to old version of ``gui.js`` from somewhere. Maybe try uninstalling and re-installing the client. If that doesn't work, try editing ``mb.manifest`` (for example by incrementing the version number in the header) so that the browser can detect that it should reload everything, and try again.

**Comment by jcass77** [comment] 2016-02-18 11:03
...I've also pushed bd703c975d436dafa1f09fa93877b4b5f3db2d31, which should at least make it obvious that the web client has not managed to connect to Mopidy.

It doesn't address the original issue, but should make these types of problems easier to identify.

**Comment by en00x** [comment] 2016-02-18 13:58
I had the same issue with Chrome on my phone, that it loads a broken version for the Pi MusicBox instead the regular one, and i cleared the cache + data to fix it, only cache won't work.

**Comment by kingosticks** [comment] 2016-02-18 14:02
Thanks @en00x. I'm not sure what Chrome calls 'data' if it's not cached data but I know the option you mean. 

Can you try clearing your 'data', @sterni1971 ?

**Comment by sterni1971** [comment] 2016-02-18 22:05
Hi! now it works. I had to clear _Cookies and other site and plugin data_
I thought that this is all about cookies, but it seems also to include
the javascript files :-O

Many thanks to all for your help.

**Closed** 2016-02-18 22:07 UTC
