### ISSUE TITLE
radio streams don't play from playlist

### ISSUE THREAD

**Issue by sbctm** [pimusicbox/mopidy-musicbox-webclient#121] opened 2015-08-21 20:58 UTC
Hi,

When I try to play a radio stream from an m3u file, no music starts to play.

in /var/log/mopidy/mopidy.log, the following lines appear, after I press the "Play swr-mp3-s-swr1rp" from the Playlist section of the musicbox webclient:

```
2015-08-21 21:36:29,943 ERROR [23936:HttpServer] mopidy.http.handlers: WebSocket request error: Expected album to be a <class 'mopidy.models.Album'>, not {u'uri': u'x', u'name': u''}
2015-08-21 21:36:29,958 ERROR [23936:HttpServer] mopidy.http.handlers: WebSocket request error: 
2015-08-21 21:36:29,998 INFO [23936:HttpServer] tornado.access: 304 GET /musicbox_webclient/images/icons/play_alt_32x32.png (192.168.125.31) 5.71ms
```

The corresponding m3u file contains a single line:
```
http://swr-mp3-s-swr1rp.akacast.akamaistream.net/7/352/137134/v1/gnl.akacast.akamaistream.net/swr-mp3-s-swr1rp
```

Original bug report, where I was told that this error is caused by the web client:
mopidy/mopidy#1262

**Comment by ferrus-manus** [comment] 2015-09-18 10:56
Same problem here.

**Comment by vasyugan** [comment] 2015-10-04 10:32
same for me, see https://github.com/mopidy/mopidy/issues/1296

**Comment by kingosticks** [comment] 2015-10-04 10:46
Sorry guys, forgot about this. I've been sitting on a fix which I'll
retest, upload and (try to) release.

**Comment by kingosticks** [comment] 2015-10-04 11:50
I tell a lie, that particular issue is already fixed in the development branch. I just need to do a release (or you can install from git if you prefer). This is actually a duplicate of #111.

**Closed by kingosticks** 2015-10-04 11:50 UTC
